apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-deployment
  labels:
    app: dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dp
  template:
    metadata:
      labels:
        app: dp
    spec:
      containers:
      - name: dp-container
        image: dp-app:latest
        imagePullPolicy: IfNotPresent #do not pull from registry / Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dp-service
spec:
  selector:
    app: dp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: None  # Headless service
