apiVersion: batch/v1
kind: Job
metadata:
  name: seed-job
spec:
  template:
    spec:
      containers:
        - name: seed-container
          image: seed-app:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: seed-service
spec:
  selector:
    app: seed
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: None  # Headless service, this allows direct access to pod IPs (for DNS resolution)